### ISSUE TITLE
Add a data migration to your scraper application

### ISSUE THREAD

**Issue by cameel** [Code-Poets/sandbox#3]
Let's start with your application that contains the `Question` and `Category` models.

- Add some questions and categories in your application.
- Remove the `Category` model.
- Add a category field to `Question` (as a `CharField`)
- Create a migration that changes the structure of the database to match the new models but **without losing the data you entered**.
- Apply the migration with `manage.py migrate` and verify that questions and categories you added have been preserved.

You can read more about data migrations in Django documentation: [Data migrations](https://docs.djangoproject.com/en/1.10/topics/migrations/#data-migrations)

**Comment by mandryl** [comment]
https://github.com/Code-Poets/sandbox/tree/mandryl-on-a-branch/mandryl/testing_app

**Comment by cameel** [comment]
@yoowul Please test the migration.

**Comment by yoowul** [comment]
Found two bugs in 0020_category.py:
1) Migration depends on '0019_auto_20161010_1421', which doesn't exist
2) Migration tries to create Category model, but it already exists after applying '0002_auto_20161006_1409'

@mandryl Please fix these issues so that the app can be tested.

**Comment by mandryl** [comment]
Code is in this branch 9877679540e00b85823ea4af3a940a1f8751f648

**Comment by mandryl** [comment]
Task is completed, migrating data turned out successful, data from Category model was preserved and migrated to a field in Question model.
